### ISSUE TITLE
Unregister the device

### ISSUE THREAD

**Issue by relez** [EddyVerbruggen/nativescript-pushy#5]
Hi @EddyVerbruggen, thanks for the plugin once more, your code makes our work much better. A quick question, is it possible to unregister using the plugin itself or do we have to use the pushy API to do so? Using the Rest API only unsubscribe the device from the topics, but it does not delete the device from receiving notifications.

If I uninstall the app and install it again and call `getDevicePushToken`, it fails. Shouldn't it send me the token again?

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

There's no "unregister" function in the SDK so I guess that's not possible. Like with the REST API it only offers unsubscribes for channels.

Their [docs](https://pushy.me/docs/ios/register-devices) also don't mention it, but *do* mention to always call "register" when the app starts (because the token may have changed).

I noticed that it may be possible on iOS to run `getDevicePushToken` before the token is received by the app from the Pushy server, so I've now changed the plugin logic to wait resolving the Promise of `getDevicePushToken` until it has received the token. That may be the problem you were seeing (although that's not too clear from your issue report). This will be part of 1.1.0 which I will release soon.
